// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ack.proto

package com.feige.im.pojo.proto;

public final class Ack {
  private Ack() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AckMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.feige.im.pojo.proto.AckMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     *消息状态
     * </pre>
     *
     * <code>.com.feige.im.pojo.proto.AckMsg.Status status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <pre>
     *消息状态
     * </pre>
     *
     * <code>.com.feige.im.pojo.proto.AckMsg.Status status = 2;</code>
     * @return The status.
     */
    com.feige.im.pojo.proto.Ack.AckMsg.Status getStatus();

    /**
     * <pre>
     *发送者
     * </pre>
     *
     * <code>string senderId = 3;</code>
     * @return The senderId.
     */
    java.lang.String getSenderId();
    /**
     * <pre>
     *发送者
     * </pre>
     *
     * <code>string senderId = 3;</code>
     * @return The bytes for senderId.
     */
    com.google.protobuf.ByteString
        getSenderIdBytes();

    /**
     * <pre>
     *接收者
     * </pre>
     *
     * <code>string receiverId = 4;</code>
     * @return The receiverId.
     */
    java.lang.String getReceiverId();
    /**
     * <pre>
     *接收者
     * </pre>
     *
     * <code>string receiverId = 4;</code>
     * @return The bytes for receiverId.
     */
    com.google.protobuf.ByteString
        getReceiverIdBytes();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.feige.im.pojo.proto.AckMsg.MsgType msgType = 5;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.feige.im.pojo.proto.AckMsg.MsgType msgType = 5;</code>
     * @return The msgType.
     */
    com.feige.im.pojo.proto.Ack.AckMsg.MsgType getMsgType();

    /**
     * <pre>
     *确认消息ID
     * </pre>
     *
     * <code>int64 ackMsgId = 8;</code>
     * @return The ackMsgId.
     */
    long getAckMsgId();

    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>uint64 timestamp = 6;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code com.feige.im.pojo.proto.AckMsg}
   */
  public  static final class AckMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.feige.im.pojo.proto.AckMsg)
      AckMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AckMsg.newBuilder() to construct.
    private AckMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AckMsg() {
      status_ = 0;
      senderId_ = "";
      receiverId_ = "";
      msgType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AckMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AckMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              senderId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverId_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 48: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 64: {

              ackMsgId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.feige.im.pojo.proto.Ack.internal_static_com_feige_im_pojo_proto_AckMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.feige.im.pojo.proto.Ack.internal_static_com_feige_im_pojo_proto_AckMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.feige.im.pojo.proto.Ack.AckMsg.class, com.feige.im.pojo.proto.Ack.AckMsg.Builder.class);
    }

    /**
     * Protobuf enum {@code com.feige.im.pojo.proto.AckMsg.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *私聊
       * </pre>
       *
       * <code>PRIVATE = 0;</code>
       */
      PRIVATE(0),
      /**
       * <pre>
       *群聊
       * </pre>
       *
       * <code>GROUP = 1;</code>
       */
      GROUP(1),
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>OTHER = 2;</code>
       */
      OTHER(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *私聊
       * </pre>
       *
       * <code>PRIVATE = 0;</code>
       */
      public static final int PRIVATE_VALUE = 0;
      /**
       * <pre>
       *群聊
       * </pre>
       *
       * <code>GROUP = 1;</code>
       */
      public static final int GROUP_VALUE = 1;
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>OTHER = 2;</code>
       */
      public static final int OTHER_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return PRIVATE;
          case 1: return GROUP;
          case 2: return OTHER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.feige.im.pojo.proto.Ack.AckMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.feige.im.pojo.proto.AckMsg.MsgType)
    }

    /**
     * Protobuf enum {@code com.feige.im.pojo.proto.AckMsg.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 已发送
       * </pre>
       *
       * <code>HAVE_SENT = 0;</code>
       */
      HAVE_SENT(0),
      /**
       * <pre>
       * 已送达
       * </pre>
       *
       * <code>ARRIVED = 1;</code>
       */
      ARRIVED(1),
      /**
       * <pre>
       * 已读
       * </pre>
       *
       * <code>HAVE_READ = 2;</code>
       */
      HAVE_READ(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 已发送
       * </pre>
       *
       * <code>HAVE_SENT = 0;</code>
       */
      public static final int HAVE_SENT_VALUE = 0;
      /**
       * <pre>
       * 已送达
       * </pre>
       *
       * <code>ARRIVED = 1;</code>
       */
      public static final int ARRIVED_VALUE = 1;
      /**
       * <pre>
       * 已读
       * </pre>
       *
       * <code>HAVE_READ = 2;</code>
       */
      public static final int HAVE_READ_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Status forNumber(int value) {
        switch (value) {
          case 0: return HAVE_SENT;
          case 1: return ARRIVED;
          case 2: return HAVE_READ;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.feige.im.pojo.proto.Ack.AckMsg.getDescriptor().getEnumTypes().get(1);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.feige.im.pojo.proto.AckMsg.Status)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <pre>
     *消息状态
     * </pre>
     *
     * <code>.com.feige.im.pojo.proto.AckMsg.Status status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     *消息状态
     * </pre>
     *
     * <code>.com.feige.im.pojo.proto.AckMsg.Status status = 2;</code>
     * @return The status.
     */
    public com.feige.im.pojo.proto.Ack.AckMsg.Status getStatus() {
      @SuppressWarnings("deprecation")
      com.feige.im.pojo.proto.Ack.AckMsg.Status result = com.feige.im.pojo.proto.Ack.AckMsg.Status.valueOf(status_);
      return result == null ? com.feige.im.pojo.proto.Ack.AckMsg.Status.UNRECOGNIZED : result;
    }

    public static final int SENDERID_FIELD_NUMBER = 3;
    private volatile java.lang.Object senderId_;
    /**
     * <pre>
     *发送者
     * </pre>
     *
     * <code>string senderId = 3;</code>
     * @return The senderId.
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送者
     * </pre>
     *
     * <code>string senderId = 3;</code>
     * @return The bytes for senderId.
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERID_FIELD_NUMBER = 4;
    private volatile java.lang.Object receiverId_;
    /**
     * <pre>
     *接收者
     * </pre>
     *
     * <code>string receiverId = 4;</code>
     * @return The receiverId.
     */
    public java.lang.String getReceiverId() {
      java.lang.Object ref = receiverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收者
     * </pre>
     *
     * <code>string receiverId = 4;</code>
     * @return The bytes for receiverId.
     */
    public com.google.protobuf.ByteString
        getReceiverIdBytes() {
      java.lang.Object ref = receiverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTYPE_FIELD_NUMBER = 5;
    private int msgType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.feige.im.pojo.proto.AckMsg.MsgType msgType = 5;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.com.feige.im.pojo.proto.AckMsg.MsgType msgType = 5;</code>
     * @return The msgType.
     */
    public com.feige.im.pojo.proto.Ack.AckMsg.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      com.feige.im.pojo.proto.Ack.AckMsg.MsgType result = com.feige.im.pojo.proto.Ack.AckMsg.MsgType.valueOf(msgType_);
      return result == null ? com.feige.im.pojo.proto.Ack.AckMsg.MsgType.UNRECOGNIZED : result;
    }

    public static final int ACKMSGID_FIELD_NUMBER = 8;
    private long ackMsgId_;
    /**
     * <pre>
     *确认消息ID
     * </pre>
     *
     * <code>int64 ackMsgId = 8;</code>
     * @return The ackMsgId.
     */
    public long getAckMsgId() {
      return ackMsgId_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>uint64 timestamp = 6;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (status_ != com.feige.im.pojo.proto.Ack.AckMsg.Status.HAVE_SENT.getNumber()) {
        output.writeEnum(2, status_);
      }
      if (!getSenderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, senderId_);
      }
      if (!getReceiverIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, receiverId_);
      }
      if (msgType_ != com.feige.im.pojo.proto.Ack.AckMsg.MsgType.PRIVATE.getNumber()) {
        output.writeEnum(5, msgType_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(6, timestamp_);
      }
      if (ackMsgId_ != 0L) {
        output.writeInt64(8, ackMsgId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (status_ != com.feige.im.pojo.proto.Ack.AckMsg.Status.HAVE_SENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_);
      }
      if (!getSenderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, senderId_);
      }
      if (!getReceiverIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, receiverId_);
      }
      if (msgType_ != com.feige.im.pojo.proto.Ack.AckMsg.MsgType.PRIVATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, msgType_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, timestamp_);
      }
      if (ackMsgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, ackMsgId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.feige.im.pojo.proto.Ack.AckMsg)) {
        return super.equals(obj);
      }
      com.feige.im.pojo.proto.Ack.AckMsg other = (com.feige.im.pojo.proto.Ack.AckMsg) obj;

      if (getId()
          != other.getId()) return false;
      if (status_ != other.status_) return false;
      if (!getSenderId()
          .equals(other.getSenderId())) return false;
      if (!getReceiverId()
          .equals(other.getReceiverId())) return false;
      if (msgType_ != other.msgType_) return false;
      if (getAckMsgId()
          != other.getAckMsgId()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderId().hashCode();
      hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverId().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + ACKMSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAckMsgId());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.feige.im.pojo.proto.Ack.AckMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feige.im.pojo.proto.Ack.AckMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feige.im.pojo.proto.Ack.AckMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feige.im.pojo.proto.Ack.AckMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feige.im.pojo.proto.Ack.AckMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.feige.im.pojo.proto.Ack.AckMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.feige.im.pojo.proto.Ack.AckMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feige.im.pojo.proto.Ack.AckMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feige.im.pojo.proto.Ack.AckMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.feige.im.pojo.proto.Ack.AckMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.feige.im.pojo.proto.Ack.AckMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.feige.im.pojo.proto.Ack.AckMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.feige.im.pojo.proto.Ack.AckMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.feige.im.pojo.proto.AckMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.feige.im.pojo.proto.AckMsg)
        com.feige.im.pojo.proto.Ack.AckMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.feige.im.pojo.proto.Ack.internal_static_com_feige_im_pojo_proto_AckMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.feige.im.pojo.proto.Ack.internal_static_com_feige_im_pojo_proto_AckMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.feige.im.pojo.proto.Ack.AckMsg.class, com.feige.im.pojo.proto.Ack.AckMsg.Builder.class);
      }

      // Construct using com.feige.im.pojo.proto.Ack.AckMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        status_ = 0;

        senderId_ = "";

        receiverId_ = "";

        msgType_ = 0;

        ackMsgId_ = 0L;

        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.feige.im.pojo.proto.Ack.internal_static_com_feige_im_pojo_proto_AckMsg_descriptor;
      }

      @java.lang.Override
      public com.feige.im.pojo.proto.Ack.AckMsg getDefaultInstanceForType() {
        return com.feige.im.pojo.proto.Ack.AckMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.feige.im.pojo.proto.Ack.AckMsg build() {
        com.feige.im.pojo.proto.Ack.AckMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.feige.im.pojo.proto.Ack.AckMsg buildPartial() {
        com.feige.im.pojo.proto.Ack.AckMsg result = new com.feige.im.pojo.proto.Ack.AckMsg(this);
        result.id_ = id_;
        result.status_ = status_;
        result.senderId_ = senderId_;
        result.receiverId_ = receiverId_;
        result.msgType_ = msgType_;
        result.ackMsgId_ = ackMsgId_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.feige.im.pojo.proto.Ack.AckMsg) {
          return mergeFrom((com.feige.im.pojo.proto.Ack.AckMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.feige.im.pojo.proto.Ack.AckMsg other) {
        if (other == com.feige.im.pojo.proto.Ack.AckMsg.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getSenderId().isEmpty()) {
          senderId_ = other.senderId_;
          onChanged();
        }
        if (!other.getReceiverId().isEmpty()) {
          receiverId_ = other.receiverId_;
          onChanged();
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (other.getAckMsgId() != 0L) {
          setAckMsgId(other.getAckMsgId());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.feige.im.pojo.proto.Ack.AckMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.feige.im.pojo.proto.Ack.AckMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <pre>
       *消息状态
       * </pre>
       *
       * <code>.com.feige.im.pojo.proto.AckMsg.Status status = 2;</code>
       * @return The enum numeric value on the wire for status.
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <pre>
       *消息状态
       * </pre>
       *
       * <code>.com.feige.im.pojo.proto.AckMsg.Status status = 2;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息状态
       * </pre>
       *
       * <code>.com.feige.im.pojo.proto.AckMsg.Status status = 2;</code>
       * @return The status.
       */
      public com.feige.im.pojo.proto.Ack.AckMsg.Status getStatus() {
        @SuppressWarnings("deprecation")
        com.feige.im.pojo.proto.Ack.AckMsg.Status result = com.feige.im.pojo.proto.Ack.AckMsg.Status.valueOf(status_);
        return result == null ? com.feige.im.pojo.proto.Ack.AckMsg.Status.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息状态
       * </pre>
       *
       * <code>.com.feige.im.pojo.proto.AckMsg.Status status = 2;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.feige.im.pojo.proto.Ack.AckMsg.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息状态
       * </pre>
       *
       * <code>.com.feige.im.pojo.proto.AckMsg.Status status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object senderId_ = "";
      /**
       * <pre>
       *发送者
       * </pre>
       *
       * <code>string senderId = 3;</code>
       * @return The senderId.
       */
      public java.lang.String getSenderId() {
        java.lang.Object ref = senderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送者
       * </pre>
       *
       * <code>string senderId = 3;</code>
       * @return The bytes for senderId.
       */
      public com.google.protobuf.ByteString
          getSenderIdBytes() {
        java.lang.Object ref = senderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送者
       * </pre>
       *
       * <code>string senderId = 3;</code>
       * @param value The senderId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者
       * </pre>
       *
       * <code>string senderId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderId() {
        
        senderId_ = getDefaultInstance().getSenderId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者
       * </pre>
       *
       * <code>string senderId = 3;</code>
       * @param value The bytes for senderId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverId_ = "";
      /**
       * <pre>
       *接收者
       * </pre>
       *
       * <code>string receiverId = 4;</code>
       * @return The receiverId.
       */
      public java.lang.String getReceiverId() {
        java.lang.Object ref = receiverId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收者
       * </pre>
       *
       * <code>string receiverId = 4;</code>
       * @return The bytes for receiverId.
       */
      public com.google.protobuf.ByteString
          getReceiverIdBytes() {
        java.lang.Object ref = receiverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收者
       * </pre>
       *
       * <code>string receiverId = 4;</code>
       * @param value The receiverId to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者
       * </pre>
       *
       * <code>string receiverId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiverId() {
        
        receiverId_ = getDefaultInstance().getReceiverId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者
       * </pre>
       *
       * <code>string receiverId = 4;</code>
       * @param value The bytes for receiverId to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverId_ = value;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.feige.im.pojo.proto.AckMsg.MsgType msgType = 5;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.feige.im.pojo.proto.AckMsg.MsgType msgType = 5;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.feige.im.pojo.proto.AckMsg.MsgType msgType = 5;</code>
       * @return The msgType.
       */
      public com.feige.im.pojo.proto.Ack.AckMsg.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        com.feige.im.pojo.proto.Ack.AckMsg.MsgType result = com.feige.im.pojo.proto.Ack.AckMsg.MsgType.valueOf(msgType_);
        return result == null ? com.feige.im.pojo.proto.Ack.AckMsg.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.feige.im.pojo.proto.AckMsg.MsgType msgType = 5;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(com.feige.im.pojo.proto.Ack.AckMsg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.com.feige.im.pojo.proto.AckMsg.MsgType msgType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private long ackMsgId_ ;
      /**
       * <pre>
       *确认消息ID
       * </pre>
       *
       * <code>int64 ackMsgId = 8;</code>
       * @return The ackMsgId.
       */
      public long getAckMsgId() {
        return ackMsgId_;
      }
      /**
       * <pre>
       *确认消息ID
       * </pre>
       *
       * <code>int64 ackMsgId = 8;</code>
       * @param value The ackMsgId to set.
       * @return This builder for chaining.
       */
      public Builder setAckMsgId(long value) {
        
        ackMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *确认消息ID
       * </pre>
       *
       * <code>int64 ackMsgId = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearAckMsgId() {
        
        ackMsgId_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>uint64 timestamp = 6;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>uint64 timestamp = 6;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>uint64 timestamp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.feige.im.pojo.proto.AckMsg)
    }

    // @@protoc_insertion_point(class_scope:com.feige.im.pojo.proto.AckMsg)
    private static final com.feige.im.pojo.proto.Ack.AckMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.feige.im.pojo.proto.Ack.AckMsg();
    }

    public static com.feige.im.pojo.proto.Ack.AckMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AckMsg>
        PARSER = new com.google.protobuf.AbstractParser<AckMsg>() {
      @java.lang.Override
      public AckMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AckMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AckMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AckMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.feige.im.pojo.proto.Ack.AckMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_feige_im_pojo_proto_AckMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_feige_im_pojo_proto_AckMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tAck.proto\022\027com.feige.im.pojo.proto\"\264\002\n" +
      "\006AckMsg\022\n\n\002id\030\001 \001(\003\0226\n\006status\030\002 \001(\0162&.co" +
      "m.feige.im.pojo.proto.AckMsg.Status\022\020\n\010s" +
      "enderId\030\003 \001(\t\022\022\n\nreceiverId\030\004 \001(\t\0228\n\007msg" +
      "Type\030\005 \001(\0162\'.com.feige.im.pojo.proto.Ack" +
      "Msg.MsgType\022\020\n\010ackMsgId\030\010 \001(\003\022\021\n\ttimesta" +
      "mp\030\006 \001(\004\",\n\007MsgType\022\013\n\007PRIVATE\020\000\022\t\n\005GROU" +
      "P\020\001\022\t\n\005OTHER\020\002\"3\n\006Status\022\r\n\tHAVE_SENT\020\000\022" +
      "\013\n\007ARRIVED\020\001\022\r\n\tHAVE_READ\020\002B\005B\003Ackb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_feige_im_pojo_proto_AckMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_feige_im_pojo_proto_AckMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_feige_im_pojo_proto_AckMsg_descriptor,
        new java.lang.String[] { "Id", "Status", "SenderId", "ReceiverId", "MsgType", "AckMsgId", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
