// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package com.feige.fim.msg.proto;

public interface BindClientReqProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.feige.fim.msg.BindClientReqProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string tags = 2;</code>
   * @return The tags.
   */
  java.lang.String getTags();
  /**
   * <code>string tags = 2;</code>
   * @return The bytes for tags.
   */
  com.google.protobuf.ByteString
      getTagsBytes();
}
