// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package com.feige.fim.msg.proto;

public interface ChatMsgReqProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.feige.fim.msg.ChatMsgReqProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg_id = 1;</code>
   * @return The msgId.
   */
  java.lang.String getMsgId();
  /**
   * <code>string msg_id = 1;</code>
   * @return The bytes for msgId.
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <code>string sequence_num = 2;</code>
   * @return The sequenceNum.
   */
  java.lang.String getSequenceNum();
  /**
   * <code>string sequence_num = 2;</code>
   * @return The bytes for sequenceNum.
   */
  com.google.protobuf.ByteString
      getSequenceNumBytes();

  /**
   * <code>int64 send_time = 3;</code>
   * @return The sendTime.
   */
  long getSendTime();

  /**
   * <code>string sender_id = 4;</code>
   * @return The senderId.
   */
  java.lang.String getSenderId();
  /**
   * <code>string sender_id = 4;</code>
   * @return The bytes for senderId.
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string receiver_id = 5;</code>
   * @return The receiverId.
   */
  java.lang.String getReceiverId();
  /**
   * <code>string receiver_id = 5;</code>
   * @return The bytes for receiverId.
   */
  com.google.protobuf.ByteString
      getReceiverIdBytes();

  /**
   * <code>string content = 6;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 6;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>int32 format = 7;</code>
   * @return The format.
   */
  int getFormat();

  /**
   * <code>int32 msg_type = 8;</code>
   * @return The msgType.
   */
  int getMsgType();

  /**
   * <code>int32 status = 9;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string extra = 10;</code>
   * @return The extra.
   */
  java.lang.String getExtra();
  /**
   * <code>string extra = 10;</code>
   * @return The bytes for extra.
   */
  com.google.protobuf.ByteString
      getExtraBytes();
}
