// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package com.feige.fim.msg.proto;

public interface ChatMsgRespProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.feige.fim.msg.ChatMsgRespProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string server_msg_id = 1;</code>
   * @return The serverMsgId.
   */
  java.lang.String getServerMsgId();
  /**
   * <code>string server_msg_id = 1;</code>
   * @return The bytes for serverMsgId.
   */
  com.google.protobuf.ByteString
      getServerMsgIdBytes();

  /**
   * <code>string client_msg_id = 2;</code>
   * @return The clientMsgId.
   */
  java.lang.String getClientMsgId();
  /**
   * <code>string client_msg_id = 2;</code>
   * @return The bytes for clientMsgId.
   */
  com.google.protobuf.ByteString
      getClientMsgIdBytes();

  /**
   * <code>int64 send_time = 3;</code>
   * @return The sendTime.
   */
  long getSendTime();
}
