// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package com.feige.fim.msg.proto;

public interface FastConnectMsgProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.feige.fim.msg.FastConnectMsgProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientId = 1;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 1;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>string sid = 2;</code>
   * @return The sid.
   */
  java.lang.String getSid();
  /**
   * <code>string sid = 2;</code>
   * @return The bytes for sid.
   */
  com.google.protobuf.ByteString
      getSidBytes();
}
