// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package com.feige.fim.msg.proto;

public interface FastConnectRespProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.feige.fim.msg.FastConnectRespProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status_code = 1;</code>
   * @return The statusCode.
   */
  int getStatusCode();
}
