// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package com.feige.fim.msg.proto;

public interface HandshakeMsgProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.feige.fim.msg.HandshakeMsgProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientKey = 1;</code>
   * @return The clientKey.
   */
  java.lang.String getClientKey();
  /**
   * <code>string clientKey = 1;</code>
   * @return The bytes for clientKey.
   */
  com.google.protobuf.ByteString
      getClientKeyBytes();

  /**
   * <code>string iv = 2;</code>
   * @return The iv.
   */
  java.lang.String getIv();
  /**
   * <code>string iv = 2;</code>
   * @return The bytes for iv.
   */
  com.google.protobuf.ByteString
      getIvBytes();

  /**
   * <code>string clientVersion = 3;</code>
   * @return The clientVersion.
   */
  java.lang.String getClientVersion();
  /**
   * <code>string clientVersion = 3;</code>
   * @return The bytes for clientVersion.
   */
  com.google.protobuf.ByteString
      getClientVersionBytes();

  /**
   * <code>string clientName = 4;</code>
   * @return The clientName.
   */
  java.lang.String getClientName();
  /**
   * <code>string clientName = 4;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <code>uint32 osCode = 5;</code>
   * @return The osCode.
   */
  int getOsCode();

  /**
   * <code>string clientId = 6;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 6;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>string token = 7;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 7;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */
  int getExtraCount();
  /**
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */
  boolean containsExtra(
      java.lang.String key);
  /**
   * Use {@link #getExtraMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExtra();
  /**
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExtraMap();
  /**
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */

  java.lang.String getExtraOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */

  java.lang.String getExtraOrThrow(
      java.lang.String key);
}
