// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package com.feige.fim.msg.proto;

public interface SuccessRespProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.feige.fim.msg.SuccessRespProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status_code = 1;</code>
   * @return The statusCode.
   */
  int getStatusCode();

  /**
   * <code>string extra = 2;</code>
   * @return The extra.
   */
  java.lang.String getExtra();
  /**
   * <code>string extra = 2;</code>
   * @return The bytes for extra.
   */
  com.google.protobuf.ByteString
      getExtraBytes();
}
